// Configuración de bancos y redes para formularios de retiro

export const boliviaBanks = [
  "Banco Mercantil",
  "Banco Nacional de Bolivia S.A.",
  "Banco de crédito de Bolivia S.A.",
  "Banco de la Nación de Argentina",
  "Banco do Brasil S.A.",
  "Banco Bisa S.A.",
  "Banco Unión S.A.",
  "Banco Solidario S.A.",
  "Banco Sol S.A.",
  "Banco Ganadero S.A.",
  "Banco Fie S.A.",
  "Banco Fortaleza S.A.",
  "Cooperativa Jesús Nazareno RL",
  "Cooperativa Fátima LTDA",
  "Cooperativa Quillacollo LTDA",
  "Pago móvil E-fectivo S.A.",
  "Móvil Entel Financiera SRL",
  "Banco PYME Ecofuturo S.A.",
  "Banco PYME de la comunidad S.A.",
  "Tibo Money",
  "Cooperativa Catedral Tarija",
  "Cooperativa San José de Bermejo LTDA",
  "Cooperativa San Anatonio RL",
  "Cooperativa San José de Punata LTDA",
  "Cooperativa Trinidad LTDA",
  "Cooperativa Comarapa RL",
  "Cooperativa San Roque RL",
  "El Choroloque RA",
  "Monseñor Felix Gainza RL",
  "Cooperativa Madre y Maestra LTDA",
  "Cooperativa Educadores Gran Chaco LTDA",
  "Cooperativa Catedral RA",
  "Cooperativa Asunción LTDA",
  "Cooperativa Magisterio Rural de Chuquisaca LTDA",
  "Cooperativa La Sagrada Familia RL",
  "Cooperativa Progreso RL",
  "Cooperativa Magisterio Rural de Chuquisaca",
  "La Primera Entidad Financiera de Vivienda",
  "Cooperativa Ina Huasi LTDA",
  "Cooperativa Loyola RL",
  "E.F. De Vivienda La Promotora",
  "Cooperativa San Martin de Porres LTDA",
  "Cooperativa San Carlos Borromeo LTDA",
];

export const walletNetworks = [
  { value: "BEP20", label: "Binance Smart Chain - BEP20 (instantáneo)" },
  { value: "MATIC", label: "Polygon - MATIC (instantáneo)" },
  { value: "TRC20", label: "Tron - TRC20 (4 días hábiles)" },
];